stages:
  - build_docker

build:docker:
  image: docker:latest
  stage: build_docker
  variables:
    PROJECT_NAME: "awscli"
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u$DOCKER_HUB_USER -p$DOCKER_HUB_PASSWORD
    - docker build -t aohorodnyk/${PROJECT_NAME}:$CI_BUILD_REF_NAME .
    - docker push aohorodnyk/${PROJECT_NAME}:$CI_BUILD_REF_NAME
  except:
    - master

build:docker:latest:
  image: docker:latest
  stage: build_docker
  variables:
    PROJECT_NAME: "awscli"
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u$DOCKER_HUB_USER -p$DOCKER_HUB_PASSWORD
    - docker build -t aohorodnyk/${PROJECT_NAME}:latest .
    - docker run --rm -tiv aohorodnyk/${PROJECT_NAME}:latest aws --version 2>&1
  only:
    - master