stages:
  - build_docker

build:docker:
  image: docker:latest
  stage: build_docker
  variables:
    PROJECT_NAME: "awscli"
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u$DOCKER_HUB_USER -p$DOCKER_HUB_PASSWORD
    - docker build -t aohorodnyk/${PROJECT_NAME}:$CI_BUILD_REF_NAME .
    - docker push aohorodnyk/${PROJECT_NAME}:$CI_BUILD_REF_NAME
  except:
    - master

build:docker:latest:
  image: docker:latest
  stage: build_docker
  variables:
    PROJECT_NAME: "awscli"
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u$DOCKER_HUB_USER -p$DOCKER_HUB_PASSWORD
    - docker build -t aohorodnyk/${PROJECT_NAME}:latest .
    - docker run -i aohorodnyk/${PROJECT_NAME}:latest aws --version 2>&1
    - DOCKER_VERSION_FULL=$(docker run --rm -tiv aohorodnyk/${PROJECT_NAME}:latest aws --version 2>&1 | grep -o '[0-9\.]\+' | head -1)
    - DOCKER_VERSION_MINOR=$(echo $DOCKER_VERSION_FULL | grep -o '[0-9]\+\.[0-9]\+' | head -1)
    - DOCKER_VERSION_MAJOR=$(echo $DOCKER_VERSION_MINOR | grep -o '[0-9]\+' | head -1)
    - docker push aohorodnyk/${PROJECT_NAME}:latest
    - docker tag aohorodnyk/${PROJECT_NAME}:latest aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_FULL}
    - docker push aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_FULL}
    - docker tag aohorodnyk/${PROJECT_NAME}:latest aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MINOR}
    - docker push aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MINOR}
    - docker tag aohorodnyk/${PROJECT_NAME}:latest aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MAJOR}
    - docker push aohorodnyk/${PROJECT_NAME}:${DOCKER_VERSION_MAJOR}
  only:
    - master